### ISSUE TITLE
Error Loading This JSON. Works fine in Android lib

### ISSUE THREAD

**Issue by chitgoks** [ngageoint/simple-features-geojson-ios#4]
#### Version Information:

  * SF GeoJSON iOS Version: 4.2.0
  * SF GeoJSON iOS Source: (e.g. CocoaPods, Source Code Build) Cocoapod
  * CocoaPods Version:
  * Xcode Version: 14.1
  * Device or Emulator: Simulator iPhone 14 pro
  * iOS Version: 15
  * Other Relevant Libraries:

#### Expected Results:

  * What did you expect to happen? - load json into FeatureCollection
  * please use this url https://www.gdacs.org/gdacsapi/api/events/geteventlist/MAP?eventtypes=EQ

#### Observed Results:

  * What happened instead? - App Crash
  * How often does this occur? - Always

#### Output:

  * Any logs, errors, or output messages?
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x113c09590'

#### Steps to Reproduce:

  1. Load json to string
  2. Use code below

#### Relevant Code:

```
if let featureCollection = SFGFeatureConverter.json(toFeatureCollection: jsonString) {
}
```

**Comment by chitgoks** [comment]
hi @bosborn what version will this change take effect? 4.2.1?

**Comment by bosborn** [comment]
Correct, which is now released

**Comment by chitgoks** [comment]
Hi @bosborn . i tried 4.2.1 and i still get the same error. this is how i loaded the json string. 
```
if let featureCollection: SFGFeatureCollection = SFGFeatureConverter.json(toFeatureCollection: jsonString) {
 ...
}
```

Am i missing something?

**Comment by bosborn** [comment]
It appears to be working for me from the JSON at the provided URL.

`pod 'sf-geojson-ios', '~> 4.2.1'`

```
let jsonString = // JSON from https://www.gdacs.org/gdacsapi/api/events/geteventlist/MAP?eventtypes=EQ

if let featureCollection: SFGFeatureCollection = SFGFeatureConverter.json(toFeatureCollection: jsonString) {
    print(featureCollection.numFeatures())
    for feature in featureCollection.features {
        print(SFGGeometryTypes.name((feature as! SFGFeature).geometryType())!)
    }
}
```

Resulting in:

```
23
Point
Polygon
Polygon
MultiPolygon
MultiPolygon
MultiPolygon
Polygon
MultiPolygon
Polygon
MultiPolygon
MultiPolygon
Point
Polygon
MultiPolygon
MultiPolygon
MultiPolygon
MultiPolygon
Point
Polygon
MultiPolygon
MultiPolygon
MultiPolygon
MultiPolygon
```
Standalone test with included hard coded JSON string:

[SFGIssue4Test.swift.zip](https://github.com/ngageoint/simple-features-geojson-ios/files/10259395/SFGIssue4Test.swift.zip)

Does that work for you?  Is there a different JSON string involved?  Make sure version 4.2.1 is used after cleaning the project?  Is the error the same or different?

**Comment by chitgoks** [comment]
Thanks. confirmed. I am not sure why but i was sure that i did update the pod. so i cleaned the build now as well just to be sure and it works ok.
